version: "3.3"
services:
  artipie:
    image: artipie/artipie:1.0-SNAPSHOT
    container_name: artipie
    restart: unless-stopped
    environment:
      - ARTIPIE_USER_NAME=artipie
      - ARTIPIE_USER_PASS=artipie
    networks:
      - artipie-net
    ports:
      - "8081:8080"
  front:
    image: artipie/front:1.0-SNAPSHOT
    container_name: front
    restart: unless-stopped
    networks:
      - artipie-net
    environment:
      - ARTIPIE_USER_NAME=artipie
      - ARTIPIE_USER_PASS=artipie
      - ARTIPIE_PORT=8080
      - ARTIPIE_LAYOUT=org
      - ARTIPIE_REST=http://artipie:8086
    ports:
      - "8080:8080"
networks:
  artipie-net:
    driver: bridge